# Generated by Django 5.0.4 on 2024-05-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=32, verbose_name='Отчество')),
                ('telephone_number', models.CharField(blank=True, max_length=24, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Электронная почта')),
                ('password', models.CharField(max_length=20, unique=True, verbose_name='пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=32, verbose_name='Отчество')),
                ('telephone_number', models.CharField(blank=True, max_length=24, verbose_name='Номер телефона')),
                ('experience', models.TextField(blank=True, verbose_name='Деятельность')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Электронная почта')),
                ('password', models.CharField(max_length=20, unique=True, verbose_name='Пароль')),
            ],
        ),
    ]
